### ISSUE TITLE
Highlighting and tooltip 'on hover' change to 'on click'

### ISSUE THREAD

**Issue by stephenjlee** [developmentseed/rem-web-demo#1]
Highlighting and tooltip on hover feels laggy when zoomed out and occludes network detail when zoomed in. Having these features on click would solve both of these problems.

**Comment by anandthakker** [comment]
@stephenjlee The last couple commits (especially dd7fe35bf006e4f1c31474024e6932476ab465c6 ) definitely improve the lagginess, but there's definitely still some lag... What do you think?

**Comment by stephenjlee** [comment]
Thanks for looking at this! It does feels better; however, I think it would still make sense to do highlight/tooltip on click as well. Both features take away from the detail we may want to show when zoomed in (e.g., seeing what houses the computer vision system got, and which ones it misses, etc.). When I zoom in w/ the satellite view and pan around, it's really hard for me to avoid highlighting the cluster I want to look at. The tooltip also blocks a good portion of the screen.

I realize tooltip-on-click probably poses a whole host of issues when panning and zooming, however. I think highlight-on-click is higher priority. Tooltip-on-click is less important.

**Comment by anandthakker** [comment]
Oh shoot! I just realized from your comment that I hadn't updated the live demo with some of the recent changes.  Just pushed them up now.  You'll see:
- Replaced tooltip with a side panel (because yeah, it was taking up a lot of screen space)
- Further improved hover highlight performance

I was thinking that we could keep the highlight/info-panel happening on hover, but then "lock" it on click so that further mouse movements wouldn't change the highlighted cluster.  A second click would "unlock".  But I'm not sure if that addresses your point:

> When I zoom in w/ the satellite view and pan around, it's really hard for me to avoid highlighting the cluster I want to look at

Was the problem here the highlighted styling, or the tooltip getting in the way?

**Comment by anandthakker** [comment]
@stephenjlee Relatedly -- I just pushed another change that highlights the area containing the given cluster, instead of the cluster itself.  It has some drawbacks, but I sorta like it better... but I'll defer to you--easy enough to revert if you prefer the previous approach

**Comment by stephenjlee** [comment]
I think your collection of fixes has really improved the concerns here. The new highlight is really cool –awesome work! I was referring to the old highlight styling before, but the new highlight totally fixes the issue!
